image: alpine:latest

variables:
  IMAGE_REPOSITORY: "${AWS_IMAGE_REPOSITORY}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID}"

stages:
  - test
  - build
  - deploy

include:
  - local: '/scripts/development.yml'
  - local: '/scripts/production.yml'
  - local: '/scripts/test.yml'
